In [5]:
import numpy as np
import pandas as pd
df = pd.read_csv('fifa_players.csv')
df

name                         full_name birth_date  age  \
0            L. Messi    Lionel Andrés Messi Cuccittini  6/24/1987   31   
1          C. Eriksen      Christian  Dannemann Eriksen  2/14/1992   27   
2            P. Pogba                        Paul Pogba  3/15/1993   25   
3          L. Insigne                   Lorenzo Insigne   6/4/1991   27   
4        K. Koulibaly                 Kalidou Koulibaly  6/20/1991   27   
...               ...                               ...        ...  ...   
17949     R. McKenzie                    Rory  McKenzie  10/7/1993   25   
17950       M. Sipľak                     Michal Sipľak   2/2/1996   23   
17951      J. Bekkema                       Jan Bekkema   4/9/1996   22   
17952      A. Al Yami               Abdulrahman Al Yami  6/19/1997   21   
17953  Júnior Brumado  José Francisco dos Santos Júnior  5/15/1999   19   

       height_cm  weight_kgs  positions   nationality  overall_rating  \
0         170.18        72.1   CF,RW,ST     Argentina              94   
1         154.94        76.2  CAM,RM,CM       Denmark              88   
2         190.50        83.9     CM,CAM        France              88   
3         162.56        59.0      LW,ST         Italy              88   
4         187.96        88.9         CB       Senegal              88   
...          ...         ...        ...           ...             ...   
17949     175.26        74.8  RM,CAM,CM      Scotland              67   
17950     182.88        79.8         LB      Slovakia              59   
17951     185.42        89.8         GK   Netherlands              59   
17952     175.26        64.9      ST,LM  Saudi Arabia              59   
17953     190.50        79.8         ST        Brazil              59   

       potential  ...  long_shots  aggression interceptions  positioning  \
0             94  ...          94          48            22           94   
1             89  ...          89          46            56           84   
2             91  ...          82          78            64           82   
3             88  ...          84          34            26           83   
4             91  ...          15          87            88           24   
...          ...  ...         ...         ...           ...          ...   
17949         70  ...          54          69            41           60   
17950         67  ...          22          62            55           42   
17951         67  ...           9          27            10            5   
17952         71  ...          58          38            15           54   
17953         75  ...          53          67            20           53   

       vision  penalties composure  marking standing_tackle  sliding_tackle  
0          94         75        96       33              28              26  
1          91         67        88       59              57              22  
2          88         82        87       63              67              67  
3          87         61        83       51              24              22  
4          49         33        80       91              88              87  
...       ...        ...       ...      ...             ...             ...  
17949      64         63        56       40              20              18  
17950      39         32        52       53              64              60  
17951      25         16        47        9              12              13  
17952      52         50        53       16              18              17  
17953      49         52        45       23              31              21  

[17954 rows x 51 columns]

In [21]:
age_array = df['age'].values
rating_array = df['overall_rating'].values

In [30]:
 age_array

array([31, 27, 25, ..., 22, 21, 19], dtype=int64)

In [40]:
age_plus_one = age_array + 1
total_rating = np.sum(rating_array)
age_plus_one

array([32, 28, 26, ..., 23, 22, 20], dtype=int64)

In [42]:
mean_age = np.mean(age_array)
median_age = np.median(age_array)


In [44]:
mean_age

25.56544502617801

In [46]:
median_age

25.0

In [48]:
std_rating = np.std(rating_array)
std_rating

6.963535852078024

In [52]:
high_rating = rating_array > 100
high_rating

array([False, False, False, ..., False, False, False])

In [54]:
high_rating_ages = age_array[high_rating]
high_rating_ages

array([], dtype=int64)

In [56]:
sequence_array = np.arange(0, 10, 2)
age_spaced = np.linspace(age_array.min(), age_array.max(), 5)


In [58]:
sequence_array

array([0, 2, 4, 6, 8])

In [60]:
age_spaced

array([17.  , 24.25, 31.5 , 38.75, 46.  ])

In [62]:
reshaped_age = age_array.reshape(-1, 2)
reshaped_age

array([[31, 27],
       [25, 27],
       [27, 27],
       ...,
       [27, 25],
       [23, 22],
       [21, 19]], dtype=int64)

In [64]:
exp_ratings = np.exp(rating_array)
log_ages = np.log(age_array)


In [68]:
log_ages

array([3.4339872 , 3.29583687, 3.21887582, ..., 3.09104245, 3.04452244,
       2.94443898])

In [70]:
exp_ratings

array([6.66317622e+40, 1.65163625e+38, 1.65163625e+38, ...,
       4.20121040e+25, 4.20121040e+25, 4.20121040e+25])

In [72]:
random_ages = np.random.randint(18, 40, 10)
random_ages

array([18, 20, 29, 30, 35, 19, 24, 28, 29, 30])

In [74]:
random_normal = np.random.normal(0, 1, 5)
random_normal

array([ 1.78399826, -0.33851039,  1.37250193, -0.97278059,  1.545561  ])

In [76]:
max_rating = np.max(rating_array)
min_rating = np.min(rating_array)
index_max_age = np.argmax(age_array)

In [78]:
max_rating

94

In [80]:
min_rating

47

In [82]:
index_max_age

1304

In [84]:
# Stack age and rating arrays vertically and horizontally
stacked_vertically = np.vstack((age_array, rating_array))
stacked_horizontally = np.hstack((age_array.reshape(-1, 1), rating_array.reshape(-1, 1)))

# Concatenate two arrays along a specific axis
concatenated_array = np.concatenate((age_array, rating_array), axis=0)


In [86]:
stacked_vertically

array([[31, 27, 25, ..., 22, 21, 19],
       [94, 88, 88, ..., 59, 59, 59]], dtype=int64)

In [88]:
stacked_horizontally

array([[31, 94],
       [27, 88],
       [25, 88],
       ...,
       [22, 59],
       [21, 59],
       [19, 59]], dtype=int64)

In [92]:
concatenated_array

array([31, 27, 25, ..., 59, 59, 59], dtype=int64)

In [94]:
ratings_over_25 = rating_array[age_array > 25]


In [96]:
ratings_over_25

array([94, 88, 88, ..., 67, 67, 67], dtype=int64)